document.querySelectorAll(".text-input").forEach((element)=>{
    element.addEventListener("blur",(event)=>{
        if(event.target.value!=""){
            event.target.nextElementSibling.classList.add("filled");
            console.log("Entro");
        }else{
            event.target.nextElementSibling.classList.remove("filled");
        }
    });
});